### ISSUE TITLE
Comparison to pdf-view-restore

### ISSUE THREAD

**Issue by mgttlinger** [nicolaisingh/saveplace-pdf-view#1]
Could you possibly say a few words in the readme how your mode compares with https://github.com/007kevin/pdf-view-restore which seems to do the same thing.

**Comment by nicolaisingh** [comment]
From code review, for each PDF file you visit in Emacs, package [`pdf-view-restore`](https://github.com/007kevin/pdf-view-restore) persists the last viewed page in a separate file.  This file is stored relative to the PDF file location.

`saveplace-pdf-view` (this package), on the other hand, persists other information like the scale amount and scroll position in addition to the last viewed page of the PDF file.  It saves those information through `save-place-mode`, an Emacs built-in for saving and restoring "places" you visit.

I'll add these to the readme, thanks for raising this.

**Comment by mgttlinger** [comment]
Ah, cool. Thanks for clarifying.
