### ISSUE TITLE
I managed to make it work for doc-view-mode

### ISSUE THREAD

**Issue by bigodel** [nicolaisingh/saveplace-pdf-view#5]
There is no need for calling the explicit `pdf-view-bookmark-jump` or `doc-view-bookmark-jump`, since both `pdf-view-mode` and `doc-view-mode` override these functions. Same for (`pdf`|`doc`)`-view-bookmark-make-record`. That being said, besides those modifications, all I did was check with `cond` if the mode is derived from `pdf-view-mode` or `doc-view-mode` instead of just checking for `pdf-view-mode`. The modifications I made also seem to remove the need for `pdf-tools` and `doc-view` as dependency, but I don't know if that would be beneficial. I would be happy to create a PR if you'd like to incorporate the changes to your package.

**Comment by nicolaisingh** [comment]
Yes please do submit a PR, I would like to take a look into it.  I don't use `doc-view-mode` personally so when I wrote this, I didn't bother to check how to implement it for that mode.

**Comment by bigodel** [comment]
there you go. sorry for the delay, had a few very full days.

**Comment by nicolaisingh** [comment]
Thanks for submitting the PR!  Apologies for the delay  It just needs some tweaks like reducing the conds, updating the docs and version.  I'll push an update soon, afterwards I'll merge it.

**Comment by bigodel** [comment]
nice! i'm interested on how you would reduce the number of `cond`'s; i've only just recently started writing my own elisp so i still fall into many bad habits.

**Comment by nicolaisingh** [comment]
@bigodel code is now merged.  If you encounter issues please do let me know.  Thanks a lot!

**Comment by bigodel** [comment]
that's great! i would just add a small change that went unnoticed when i made the PR: `doc-view` has its own `doc-view-bookmark-jump` as well.
