### ISSUE TITLE
Add a tag

### ISSUE THREAD

**Issue by abcdw** [nicolaisingh/saveplace-pdf-view#7]
Hi, thank you very much for the package!

Can you place a git tag, please?  Having it will make it easier to package it in GNU/Linux distributions/package managers.

**Comment by nicolaisingh** [comment]
Hi, tags have been added.  May I ask which distro/package manager is this, if there are any plans to add this package?
thank you as well!

**Comment by abcdw** [comment]
Nicolai Singh ***@***.***> writes:

> Hi, tags have been added.  May I ask which distro/package manager is
> this, if there are any plans to add this package?  thank you as well!

`saveplace-pdf-view-1.0.4` is kinda unusual tag format)

Thank you for placing a tag, will make a package for GNU Guix soon.

**Comment by abcdw** [comment]
Finished a package recipe, you can track the status here:
http://issues.guix.gnu.org/49318

**Comment by nicolaisingh** [comment]
thanks!
